language: go

matrix:
  fast_finish: true
  include:
    - go: 1.12.x
      env: GO111MODULE=on
    - go: 1.13.x
    - go: 1.14.x
    - go: 1.15.x
    - go: master

git:
  depth: 10

before_install:
  - if [[ "${GO111MODULE}" = "on" ]]; then mkdir "${HOME}/go"; export GOPATH="${HOME}/go"; fi

install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; fi
  - if [[ "${GO111MODULE}" = "on" ]]; then export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"; fi

go_import_path: github.com/CyrivlClth/go-tools

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
